name: Subscribe Email Address
on: 
  workflow_dispatch:
    inputs:
      emailAddress:
        description: "Email Address"
        required: true
        type: string

jobs:
  updateSubscribersTable:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.event.inputs.emailAddress }}